version: '3.8'

services:
  react:
    container_name: react
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - build_react:/var/www/html
    ports:
      - '5173:3000'

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - 120:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - react

volumes:
  build_react: