services:
  postgres_test:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./back-end/.env.test

  node_test:
    container_name: node
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_test
    env_file:
      - ./back-end/.env.test