name: React CI Workflow

on:
  [pull_request]

jobs:
  react-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "passwords"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/passwords"
          directory: back-end
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_test npm run test